[project]
name = "adobe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = []

[tool.uv.workspace]
members = [
    "pipelines/relighting-pipeline",
    "pipelines/agent",
]
