data_root_dir: /home/tmp_adm/adobe/LaMa_Final/orin
out_root_dir: /home/tmp_adm/adobe/LaMa_Final/orin/experiments
tb_dir: /home/tmp_adm/adobe/LaMa_Final/orin/tb_logs
pretrained_models: /home/tmp_adm/adobe/LaMa_Final/orin/pre_trained_models
