name: grade
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - anaconda-anon-usage=0.7.4=pyhb46e38b_100
  - anaconda-auth=0.10.0=py313h06a4308_1
  - anaconda-cli-base=0.6.0=py313h06a4308_0
  - annotated-types=0.6.0=py313h06a4308_1
  - archspec=0.2.5=pyhd3eb1b0_0
  - boltons=25.0.0=py313h06a4308_0
  - brotlicffi=1.0.9.2=py313hbdd6827_2
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2025.11.4=h06a4308_0
  - certifi=2025.11.12=py313h06a4308_0
  - cffi=2.0.0=py313h4eded50_1
  - charset-normalizer=3.4.4=py313h06a4308_0
  - click=8.1.8=py313h06a4308_0
  - conda=25.11.0=py313h06a4308_0
  - conda-anaconda-telemetry=0.3.0=pyhd3eb1b0_1
  - conda-anaconda-tos=0.2.2=py313h06a4308_1
  - conda-content-trust=0.2.0=py313h06a4308_1
  - conda-libmamba-solver=25.4.0=pyhdf14ebd_1
  - conda-package-handling=2.4.0=py313h06a4308_1
  - conda-package-streaming=0.12.0=py313h06a4308_1
  - cpp-expected=1.1.0=hdb19cb5_0
  - cryptography=46.0.3=py313h0a354b3_0
  - dbus=1.16.2=h5bd4931_0
  - distro=1.9.0=py313h06a4308_0
  - expat=2.7.3=h3385a95_0
  - fmt=11.2.0=hca5f364_0
  - frozendict=2.4.6=py313hee96239_0
  - gettext=0.21.0=hedfda30_2
  - h11=0.16.0=py313h06a4308_1
  - icu=73.1=h6a678d5_0
  - idna=3.11=py313h06a4308_0
  - jansson=2.14=h5eee18b_1
  - jaraco.classes=3.4.0=py313h06a4308_0
  - jaraco.context=6.0.0=py313h06a4308_0
  - jaraco.functools=4.1.0=py313h06a4308_0
  - jeepney=0.7.1=pyhd3eb1b0_0
  - jsonpatch=1.33=py313h06a4308_1
  - jsonpointer=3.0.0=py313h06a4308_0
  - keyring=25.6.0=py313h06a4308_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libarchive=3.8.2=h3ec8f01_0
  - libcurl=8.16.0=heebcbe5_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.8=hf80d704_0
  - libmamba=2.3.2=h4368100_0
  - libmambapy=2.3.2=py313hea2f153_0
  - libmpdec=4.0.0=h5eee18b_0
  - libnghttp2=1.67.1=h697f920_0
  - libsolv=0.7.30=h6f1ccf3_2
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libunistring=1.3=hb25bd0a_0
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - markdown-it-py=4.0.0=py313h06a4308_0
  - mdurl=0.1.2=py313h06a4308_0
  - menuinst=2.4.1=py313h06a4308_1
  - more-itertools=10.8.0=py313h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - nlohmann_json=3.11.2=h6a678d5_0
  - openssl=3.0.18=hd6dcaed_0
  - packaging=25.0=py313h06a4308_1
  - pcre2=10.46=hf426167_0
  - pip=25.2=pyhc872135_1
  - pkce=1.0.3=py313h06a4308_0
  - platformdirs=4.5.0=py313h06a4308_0
  - pluggy=1.5.0=py313h06a4308_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pybind11-abi=5=hd3eb1b0_0
  - pycosat=0.6.6=py313h5eee18b_2
  - pycparser=2.23=py313h06a4308_0
  - pydantic=2.12.3=py313h06a4308_1
  - pydantic-core=2.41.4=py313h498d7c9_0
  - pydantic-settings=2.10.1=py313h06a4308_0
  - pygments=2.19.2=py313h06a4308_0
  - pyjwt=2.10.1=py313h06a4308_0
  - pysocks=1.7.1=py313h06a4308_1
  - python=3.13.9=h7e8bc2b_100_cp313
  - python-dotenv=1.1.0=py313h06a4308_0
  - python_abi=3.13=1_cp313
  - readchar=4.2.1=py313h06a4308_0
  - readline=8.3=hc2a1206_0
  - reproc=14.2.4=h6a678d5_2
  - reproc-cpp=14.2.4=h6a678d5_2
  - requests=2.32.5=py313h06a4308_1
  - rich=14.2.0=py313h06a4308_0
  - ruamel.yaml.clib=0.2.14=py313h4aee224_0
  - secretstorage=3.4.0=py313h3e8c6aa_0
  - semver=3.0.4=py313h06a4308_0
  - setuptools=80.9.0=py313h06a4308_0
  - shellingham=1.5.4=py313h06a4308_0
  - simdjson=3.10.1=hdb19cb5_0
  - sqlite=3.51.0=h2a70700_0
  - tk=8.6.15=h54e0aa7_0
  - tomli=2.2.1=py313h06a4308_0
  - tqdm=4.67.1=py313h7040dfc_1
  - truststore=0.10.1=py313h06a4308_1
  - typer=0.17.4=py313h06a4308_0
  - typing-extensions=4.15.0=py313h06a4308_0
  - typing-inspection=0.4.2=py313h06a4308_0
  - typing_extensions=4.15.0=py313h06a4308_0
  - urllib3=2.5.0=py313h06a4308_0
  - uvicorn=0.35.0=py313h06a4308_0
  - wheel=0.45.1=py313h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml-cpp=0.8.0=h6a678d5_1
  - zlib=1.3.1=hb25bd0a_0
  - zstandard=0.24.0=py313h3d778a8_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - accelerate==1.12.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - alabaster==1.0.0
      - annotated-doc==0.0.4
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - asttokens==3.0.1
      - attrs==25.4.0
      - babel==2.17.0
      - backcall==0.2.0
      - backoff==2.2.1
      - beautifulsoup4==4.14.3
      - black==25.11.0
      - bleach==6.3.0
      - botocore==1.41.6
      - braceexpand==0.1.7
      - coloredlogs==15.0.1
      - contextlib2==21.6.0
      - coverage==7.12.0
      - datasets==2.17.0
      - decorator==5.2.1
      - deprecation==2.1.0
      - diffusers==0.35.2
      - dill==0.3.8
      - docopt==0.6.2
      - docutils==0.22.3
      - easydict==1.13
      - executing==2.2.1
      - fastapi==0.123.0
      - filelock==3.20.0
      - flatbuffers==25.9.23
      - frozenlist==1.8.0
      - fsspec==2023.10.0
      - gdown==4.7.1
      - gitdb==4.0.12
      - gitpython==3.1.42
      - h5py==3.15.1
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - imageio==2.37.2
      - imagesize==1.4.1
      - importlib-metadata==8.7.0
      - ipython==8.12.3
      - jedi==0.19.2
      - jinja2==3.1.6
      - jmespath==1.0.1
      - joblib==1.5.2
      - kaggle==1.8.2
      - kagglesdk==0.1.13
      - kornia==0.6.12
      - kornia-rs==0.1.10
      - lazy-loader==0.4
      - librt==0.6.3
      - lightning-utilities==0.15.2
      - markupsafe==3.0.3
      - matplotlib-inline==0.2.1
      - ml-dtypes==0.5.4
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.16
      - mypy==1.19.0
      - mypy-extensions==1.1.0
      - networkx==3.6
      - numpy==2.2.6
      - numpydoc==1.9.0
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - omegaconf==2.3.0
      - onnx==1.18.0
      - onnx-ir==0.1.12
      - onnxruntime==1.22.1
      - onnxscript==0.5.6
      - opencv-python==4.12.0.88
      - pandas==2.2.3
      - parso==0.8.5
      - pathspec==0.12.1
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==11.3.0
      - pipreqs==0.4.13
      - prettytable==3.11.0
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - protobuf==6.31.1
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==19.0.1
      - pyarrow-hotfix==0.7
      - pydantic-yaml==1.4.0
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.20
      - python-slugify==8.0.4
      - pytokens==0.3.0
      - pytorch-lightning==2.6.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - qai-hub==0.41.0
      - qai-hub-models==0.42.0
      - regex==2025.11.3
      - requests-toolbelt==1.0.0
      - roman-numerals==3.1.0
      - ruamel-yaml==0.18.10
      - s3transfer==0.13.1
      - safetensors==0.7.0
      - schema==0.7.5
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - snowballstemmer==3.0.1
      - soupsieve==2.8
      - sphinx==9.0.1
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - stack-data==0.6.3
      - starlette==0.50.0
      - sympy==1.14.0
      - tabulate==0.9.0
      - text-unidecode==1.3
      - threadpoolctl==3.6.0
      - tifffile==2025.10.16
      - tokenizers==0.22.1
      - torch==2.9.1
      - torchmetrics==1.8.2
      - torchvision==0.24.1
      - traitlets==5.14.3
      - transformers==4.57.3
      - triton==3.5.1
      - typer-slim==0.20.0
      - types-requests==2.32.4.20250913
      - types-tqdm==4.67.0.20250809
      - tzdata==2025.2
      - wcwidth==0.2.14
      - webdataset==1.0.2
      - webencodings==0.5.1
      - xxhash==3.6.0
      - yarg==0.1.10
      - yarl==1.22.0
      - zipp==3.23.0
prefix: /home/tmp_adm/miniconda3
